services:

  pickleball-generate:
    image: pickleball-generate
    build:
      dockerfile: Dockerfile.generate
    volumes:
      - .:/pickleball
    command: /bin/bash

  pickleball-enforce:
    image: pickleball-enforce
    build:
      context: ./enforce/
      dockerfile: Dockerfile

  pickleball-enforce-deb11:
    image: pickleball-enforce-deb11
    build:
      context: ./enforce/
      dockerfile: Dockerfile.deb11

  generate-all:
    image: pickleball-generate-evaluation
    build:
      context: ./evaluation/
      dockerfile: Dockerfile.evaluate
    depends_on:
      - pickleball-generate
    volumes:
      - .:/pickleball
    command: /pickleball/evaluation/policy-evaluation.sh

  #
  # Evaluate enforcement
  #
  
  enforce-conch:
    image: pickleball-enforce-conch
    build:
      context: ./evaluation/
      dockerfile: ./enforcement/Dockerfile.conch
    depends_on:
      - generate-all
      - pickleball-enforce
    volumes:
      - ${BENIGN_MODELS}:/models/benign
      - ${MALICIOUS_MODELS}:/models/malicious
      - ./evaluation/policies/conch.json:/root/policies/policy.json
      - .:/pickleball
    command: /pickleball/evaluation/enforcement/load_all.py --all-model-path /models/benign/conch --library conch

  enforce-flagembedding:
    image: pickleball-enforce-flagembedding
    build:
      context: ./evaluation/
      dockerfile: ./enforcement/Dockerfile.flagembedding
    depends_on:
      - generate-all
      - pickleball-enforce
    volumes:
      - ${BENIGN_MODELS}:/models/benign
      - ${MALICIOUS_MODELS}:/models/malicious
      - ./evaluation/policies/flagembedding.json:/root/policies/policy.json
      - .:/pickleball
    command: /pickleball/evaluation/enforcement/load_all.py --all-model-path /models/benign/flagembedding --library flagembedding

  enforce-flair:
    image: pickleball-enforce-flair
    build:
      context: ./evaluation/enforcement/
      dockerfile: Dockerfile.flair
    depends_on:
      - generate-all
      - pickleball-enforce
    volumes:
      - ${BENIGN_MODELS}:/models/benign
      - ${MALICIOUS_MODELS}:/models/malicious
      - ./evaluation/policies/flair.json:/root/policies/policy.json
      - .:/pickleball
    command: /pickleball/evaluation/enforcement/load_all.py --all-model-path /models/benign/flair --library flair

  enforce-gliner:
    image: pickleball-enforce-gliner
    build:
      context: ./evaluation/enforcement/
      dockerfile: Dockerfile.gliner
    depends_on:
      - generate-all
      - pickleball-enforce
    volumes:
      - ${BENIGN_MODELS}:/models/benign
      - ${MALICIOUS_MODELS}:/models/malicious
      - ./evaluation/policies/gliner.json:/root/policies/policy.json
      - .:/pickleball
    command: /pickleball/evaluation/enforcement/load_all.py --all-model-path /models/benign/gliner --library gliner

  # TODO: Determine why this is fetching models remotely
  enforce-huggingsound:
    image: pickleball-enforce-huggingsound
    build:
      context: ./evaluation/
      dockerfile: ./enforcement/Dockerfile.huggingsound
    depends_on:
      - generate-all
      - pickleball-enforce-deb11
    volumes:
      - ${BENIGN_MODELS}:/models/benign
      - ${MALICIOUS_MODELS}:/models/malicious
      - ./evaluation/policies/huggingsound.json:/root/policies/policy.json
      - .:/pickleball
    command: /pickleball/evaluation/enforcement/load_all.py --all-model-path /models/benign/huggingsound --library huggingsound

  enforce-languagebind:
    image: pickleball-enforce-languagebind
    build:
      context: ./evaluation/
      dockerfile: ./enforcement/Dockerfile.languagebind
    depends_on:
      - generate-all
      - pickleball-enforce-deb11
    volumes:
      - ${BENIGN_MODELS}:/models/benign
      - ${MALICIOUS_MODELS}:/models/malicious
      - ./evaluation/policies/languagebind.json:/root/policies/policy.json
      - .:/pickleball
    command: /pickleball/evaluation/enforcement/load_all.py --all-model-path /models/benign/languagebind --library languagebind

  enforce-melotts:
    image: pickleball-enforce-melotts
    build:
      context: ./evaluation/
      dockerfile: ./enforcement/Dockerfile.melotts
    depends_on:
      - generate-all
      - pickleball-enforce
    volumes:
      - ${BENIGN_MODELS}:/models/benign
      - ${MALICIOUS_MODELS}:/models/malicious
      - ./evaluation/policies/melotts.json:/root/policies/policy.json
      - .:/pickleball
    command: /pickleball/evaluation/enforcement/load_all.py --all-model-path /models/benign/melo --library melotts

  enforce-parrot:
    image: pickleball-enforce-parrot
    build:
      context: ./evaluation/
      dockerfile: ./enforcement/Dockerfile.parrot
    depends_on:
      - generate-all
      - pickleball-enforce
    volumes:
      - ${BENIGN_MODELS}:/models/benign
      - ${MALICIOUS_MODELS}:/models/malicious
      - ./evaluation/policies/parrot.json:/root/policies/policy.json
      - .:/pickleball
    command: /pickleball/evaluation/enforcement/load_all.py --all-model-path /models/benign/Parrot --library parrot

  enforce-pyannote:
    image: pickleball-enforce-pyannote
    build:
      context: ./evaluation/
      dockerfile: ./enforcement/Dockerfile.pyannote
    depends_on:
      - generate-all
      - pickleball-enforce
    volumes:
      - ${BENIGN_MODELS}:/models/benign
      - ${MALICIOUS_MODELS}:/models/malicious
      - ./evaluation/policies/pyannote.json:/root/policies/policy.json
      - .:/pickleball
    command: /pickleball/evaluation/enforcement/load_all.py --all-model-path /models/benign/pyannote-audio --library pyannote

  enforce-all:
    image: pickleball-enforce
    command: ["echo", "All model load tests completed"]
    depends_on:
      enforce-conch:
        condition: service_completed_successfully
      enforce-flagembedding:
        condition: service_completed_successfully
      enforce-flair:
        condition: service_completed_successfully
      enforce-gliner:
        condition: service_completed_successfully
      enforce-huggingsound:
        condition: service_completed_successfully
      enforce-languagebind:
        condition: service_completed_successfully
      enforce-melotts:
        condition: service_completed_successfully
      enforce-parrot:
        condition: service_completed_successfully
      enforce-pyannote:
        condition: service_completed_successfully
