services:

  pickleball-generate:
    image: pickleball-generate
    build:
      dockerfile: Dockerfile.generate
    volumes:
      - .:/pickleball
    command: /bin/bash

  pickleball-enforce:
    image: pickleball-enforce
    build:
      context: ./enforce/
      dockerfile: Dockerfile

  pickleball-enforce-deb11:
    image: pickleball-enforce-deb11
    build:
      context: ./enforce/
      dockerfile: Dockerfile.deb11

  generate-all:
    image: pickleball-generate-evaluation
    build:
      context: ./evaluation/
      dockerfile: Dockerfile.evaluate
    depends_on:
      - pickleball-generate
    volumes:
      - .:/pickleball
    command: /pickleball/evaluation/policy-evaluation.sh

  enforce-flair:
    image: pickleball-enforce-flair
    build:
      context: ./evaluation/enforcement/
      dockerfile: Dockerfile.flair
    depends_on:
      - generate-all
      - pickleball-enforce
    volumes:
      - ${BENIGN_MODELS}:/models/benign
      - ${MALICIOUS_MODELS}:/models/malicious
      - ./evaluation/policies/flair.json:/root/policies/policy.json
      - .:/pickleball
    command: /pickleball/evaluation/enforcement/try_all.py --all-model-path /models/benign/flair


