FROM debian:11

RUN apt update && apt install -y python3-dev python3-pip python3-venv vim

WORKDIR /root

ENV VIRTUAL_ENV=/root/pickle-venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY enforce.py /usr/lib/python3.9/pickle.py
RUN pip3 install torch==2.5.0+cpu torchvision==0.20.0 torchaudio==2.5.0 --index-url https://download.pytorch.org/whl/cpu
RUN pip3 install transformers==4.46.1

RUN mkdir -p /root/policies
WORKDIR /load-model
