ALLOWED_CALLABLES = [
    'from collections import OrderedDict',
    'from torch.nn.parameter import Parameter',
    'from torch.nn.serialization import _get_layout',
    'from torch import Size',
    'from torch import Tensor',

    'from torch import complex32',
    'from torch import complex64',
    'from torch import complex128',
    'from torch import float8_e5m2',
    'from torch import float8_e4m3fn',
    'from torch import float8_e5m2fnuz',
    'from torch import float8_e4m3fnuz',
    'from torch import float16',
    'from torch import float32',
    'from torch import float64',
    'from torch import int8',
    'from torch import int16',
    'from torch import int32',
    'from torch import int64',

    'from torch import DoubleStorage',
    'from torch import FloatStorage',
    'from torch import HalfStorage',
    'from torch import LongStorage',
    'from torch import IntStorage',
    'from torch import ShortStorage',
    'from torch import CharStorage',
    'from torch import ByteStorage',
    'from torch import BoolStorage',
    'from torch import BFloat16Storage',
    'from torch import ComplexDoubleStorage',
    'from torch import ComplexFloatStorage',
    'from torch import QInt8Storage',
    'from torch import QInt32Storage',
    'from torch import QUInt8Storage',
    'from torch import QUint4x2Storage',
    'from torch import QUInt2x4Storage',

    'from torch._utils import _rebuild_parameter',
    'from torch._utils import _rebuild_tensor',
    'from torch._utils import _rebuild_tensor_v2',
    'from torch._utils import _rebuild_tensor_v3',
    'from torch._utils import _rebuild_sparse_tensor',
    'from torch._utils import _rebuild_meta_tensor_no_storage',
    'from torch._utils import _rebuild_nested_tensor',
]